### ISSUE TITLE
Manage system lifecycle using system_modes interface

### ISSUE THREAD

**Issue by chcorbato** [micro-ROS/system_modes#25]
I think to configure and activate a system currently you need to use the `lifecycle` services. You cannot use the system_modes services unless the system is already in the active state, right?

For example, in the `system_modes_examples`, right after launching the bringup files, so with the system in no state yet, this does not work:
```
ros2 service call /actuation/change_mode system_modes/srv/ChangeMode "{node_name: actuation, mode_name: active}"
waiting for service to become available...
requester: making request: system_modes.srv.ChangeMode_Request(node_name='actuation', mode_name='active')

response:
system_modes.srv.ChangeMode_Response(success=False)
```

I think it would be useful if the system_mode interface also allows to configure and activate systems.

**Comment by chcorbato** [comment]
I was using incorrect transitions IDs, apologies. I close the issue.

**Comment by norro** [comment]
The mode manager already provides the state interface (`.../change_state`, etc) for systems, e.g. to activate them. Is that what you mean?

Or do you mean that the mode manager should take care of ensuring that a system is active first, before transitioning it into a certain mode? This should be dependent on this issue then: https://github.com/micro-ROS/system_modes/issues/27

**Comment by chcorbato** [comment]
> The mode manager already provides the state interface (`.../change_state`, etc) for systems, e.g. to activate them. Is that what you mean?

This is what I meant.

> Or do you mean that the mode manager should take care of ensuring that a system is active first, before transitioning it into a certain mode? This should be dependent on this issue then: #27

Great, this is a separate problem, related to self-managing systems. I will elaborate my viewpoint, also in relation to the metacontroller, in #27
